# .github/workflows/parser.yml

name: realty-parser

on:
  schedule: # раз в час
    - cron: '0 * * * *'
  workflow_dispatch: # запуск вручную

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4 # 1) код
      
      # 2) кэш-шаг: новый key → всегда «save»; restore-keys подбирает посл. версию
      - name: Cache DB
        id: db-cache
        uses: actions/cache@v3
        with:
          path: offers.db
          key: offers-db-${{ github.run_id }} # <- уникален для run
          restore-keys: |
            offers-db- # ищем любой предыдущий
      
      # 3) Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install deps
        run: python -m pip install --upgrade pip requests
      
      # 4) запуск парсера
      - name: Run parser
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_IDS: ${{ secrets.CHAT_IDS }}
          YANDEX_GEOCODER_API_KEY: ${{ secrets.YANDEX_GEOCODER_API_KEY }}
          DESTINATION_ADDRESS: ${{ secrets.DESTINATION_ADDRESS }}
        run: python parser.py
        
      # 5) логирование статистики
      - name: Show DB stats
        run: |
          if [ -f offers.db ]; then
            echo "База данных существует"
            python3 -c "
          import sqlite3
          try:
              conn = sqlite3.connect('offers.db')
              cur = conn.cursor()
              cur.execute('SELECT COUNT(*) FROM offers')
              total = cur.fetchone()[0]
              print(f'Всего объявлений: {total}')
              cur.execute('SELECT COUNT(DISTINCT url) FROM sent')
              sent = cur.fetchone()[0]
              print(f'Отправлено уникальных: {sent}')
              try:
                  cur.execute('SELECT COUNT(*) FROM offers WHERE travel_time IS NOT NULL')
                  with_time = cur.fetchone()[0]
                  print(f'С временем в пути: {with_time}')
              except:
                  pass
              conn.close()
          except Exception as e:
              print(f'Ошибка статистики: {e}')
          "
          else
            echo "База данных не найдена"
          fi
