# .github/workflows/parser.yml
name: realty-parser

on:
  schedule:
    - cron: '*/20 * * * *'     # каждые 15 мин (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    # 1. Код
    - uses: actions/checkout@v4

    # 2. Скачиваем предыдущий offers.db → _restore/
    - name: Download DB artifact
      id: restore
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: db
        path: _restore          # <-- кладём сюда
        if-no-files-found: ignore

    # 3. Переносим файл в корень, если он существует
    - name: Move DB to workspace root
      if: hashFiles('_restore/offers.db') != ''
      run: mv _restore/offers.db ./offers.db

    # 4. Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install deps
      run: python -m pip install --upgrade pip requests

    # 5. Запуск парсера
    - name: Run parser
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        CHAT_IDS:     ${{ secrets.CHAT_IDS }}
      run: python parser.py

    # 6. Загружаем обновлённую базу
    - name: Upload DB artifact
      uses: actions/upload-artifact@v4
      with:
        name: db
        path: offers.db
        retention-days: 30
