# .github/workflows/parser.yml
#
# Workflow запускает ваш скрипт parser.py каждые 15 минут
# и по кнопке «Run workflow».  Файл offers.db хранится в артефакте
# db, поэтому база не теряется между запусками.
# В репозитории НЕТ requirements.txt, поэтому ставим единственную
# зависимость — requests — прямо командой pip install requests.

name: realty-parser

on:
  schedule:
    - cron: "*/15 * * * *"          # ⏰ каждые 15 минут (UTC)
  workflow_dispatch:                # ▶ ручной запуск

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1 — Клонируем репозиторий
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2 — Пробуем забрать предыдущую offers.db
      - name: Restore DB
        uses: actions/download-artifact@v4
        continue-on-error: true              # если файла нет — не падаем
        with:
          name: db
          path: .
          if-no-files-found: ignore

      # 3 — Устанавливаем Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 4 — Ставим requests (requirements.txt в проекте нет)
      - name: Install deps
        run: |
          python -m pip install --upgrade pip requests

      # 5 — Запускаем парсер
      - name: Run parser
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_IDS:     ${{ secrets.CHAT_IDS }}   # строка «id1,id2,id3»
        run: python parser.py                     # ← ваш основной файл

      # 6 — Сохраняем/обновляем offers.db
      - name: Upload DB
        uses: actions/upload-artifact@v4
        with:
          name: db
          path: offers.db
          retention-days: 30
