# .github/workflows/parser.yml
# Запускает парсер каждые 15 минут и вручную по кнопке “Run workflow”.

name: realty-parser

on:
  schedule:                # ⏰ CRON-расписание (UTC)
    - cron: '*/20 * * * *' #   
  workflow_dispatch:       # ▶️ возможность запустить вручную из вкладки Actions

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем репозиторий
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Пытаемся скачать предыдущий offers.db
      #    При первом запуске файла ещё нет, поэтому errors → ignore
      - name: Restore DB artifact
        uses: actions/download-artifact@v4
        with:
          name: db
          path: .
          if-no-files-found: ignore   # ← ключевая строчка

      # 3) Устанавливаем Python-среду
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'      # можно 3.10+

      # 4) Ставим зависимости
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 5) Запускаем парсер
      - name: Run parser
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_IDS:     ${{ secrets.CHAT_IDS }}          # строка "id1,id2,id3"
        run: python realty_fullfeed.py

      # 6) Сохраняем/обновляем базу как артефакт
      - name: Upload DB artifact
        uses: actions/upload-artifact@v4
        with:
          name: db
          path: offers.db
          retention-days: 30            # хранить 30 дней (по-желанию)
