# .github/workflows/parser.yml
# Стартует каждые 15 мин и по кнопке «Run workflow».
# База offers.db хранится в кэше actions/cache → никакой повторной рассылки.

name: realty-parser

on:
  schedule:
    - cron: "*/20 * * * *"          # ⏰ каждые 15 минут (UTC)
  workflow_dispatch:                # ▶ ручной запуск

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    # 1. Код
    - uses: actions/checkout@v4

    # 2. Восстанавливаем (и в конце сохраняем) offers.db через cache
    - name: Restore / save DB (cache)
      uses: actions/cache@v3
      with:
        path: offers.db            # где лежит файл
        key: offers-db             # постоянный ключ → один и тот же файл
        # Если файл ещё не создан, cache просто пропустится.

    # 3. Python
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install deps
      run: python -m pip install --upgrade pip requests

    # 4. Запускаем парсер
    - name: Run parser
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        CHAT_IDS:     ${{ secrets.CHAT_IDS }}
      run: python parser.py
